---
- name: Update Ubuntu Server
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all installed packages
      apt:
        upgrade: full
        autoremove: yes
        autoclean: yes

    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_flag

    - name: Reboot the server if needed
      reboot:
      when: reboot_flag.stat.exists
